# Generated by Django 5.0.9 on 2024-11-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("review", models.CharField(max_length=255)),
                ("lon", models.FloatField()),
                ("lat", models.FloatField()),
            ],
        ),
    ]
