# Generated by Django 5.0.9 on 2024-11-21 16:19

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donut", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                default=Point(10, 10, srid=4326)
            ),
            preserve_default=False,
        ),
    ]
