# Generated by Django 5.0.9 on 2024-11-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donut", "0002_shop_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="address_line_1",
            field=models.CharField(default="asdf", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shop",
            name="address_line_2",
            field=models.CharField(default="asdf", max_length=255),
            preserve_default=False,
        ),
    ]
